DrFaust92/terraform-provider-bitbucket

bitbucket/provider.go
bitbucket/resource_branching_model.go
bitbucket/resource_branching_model_test.go
docs/resources/branching_model.md

--- PASS: TestAccBitbucketBranchingModel_basic (32.77s)
--- PASS: TestAccBitbucketBranchingModel_production (34.47s)
--- PASS: TestAccBitbucketBranchingModel_branchTypes (32.94s)

Add Support for Branching model

---

bitbucket/data_current_user.go
bitbucket/data_user.go
bitbucket/provider.go
bitbucket/resource_default_reviewers.go
bitbucket/resource_default_reviewers_test.go
docs/data-sources/current_user.md
docs/resources/default_reviewers.md

--- PASS: TestAccBitbucketDefaultReviewers_basic (41.48s)

Default reviewers import + Current User data source

---

bitbucket/data_current_user.go
bitbucket/data_current_user_test.go
bitbucket/data_user.go
bitbucket/data_user_test.go
docs/data-sources/current_user.md
docs/data-sources/user.md

--- PASS: TestAccCurrentUser_basic (27.34s)

current user datasource + tests and email support

---

bitbucket/resource_hook.go
bitbucket/resource_hook_test.go
docs/resources/hook.md

--- PASS: TestAccBitbucketHook_basic (82.08s)

Hook Import

---

bitbucket/resource_branch_restriction.go
bitbucket/resource_branch_restriction_test.go
docs/resources/branch_restriction.md
docs/resources/hook.md

--- PASS: TestAccBitbucketBranchRestriction_basic (38.93s)
--- PASS: TestAccBitbucketBranchRestriction_model (39.08s)

Branch Restriction Import

---

bitbucket/provider.go
bitbucket/resource_ssh_key.go
bitbucket/resource_ssh_key_test.go
bitbucket/utils.go
docs/resources/ssh_key.md

Closes #10 
--- PASS: TestAccBitbucketSshKey_basic (42.22s)
--- PASS: TestAccBitbucketSshKey_label (65.23s)

SSH Key resource

---

bitbucket/resource_project.go
bitbucket/resource_project_test.go
docs/resources/project.md

--- PASS: TestAccBitbucketProject_basic (35.30s)
--- PASS: TestAccBitbucketProject_avatar (38.41s)

Project - deprecate old endpoint + avatar support

---

.gitignore
bitbucket/resource_branch_restriction.go

i used this to figure out if the code was broken
turns out my mental model of Bitbucket's API was broken

branch restriction logging

---

bitbucket/provider.go
bitbucket/resource_workspace_hook.go
bitbucket/resource_workspace_hook_test.go
docs/resources/workspace_hook.md

Workspace hook

---

bitbucket/data_ip_ranges.go
bitbucket/data_ip_ranges_test.go
bitbucket/provider.go
docs/data-sources/current_user.md
docs/data-sources/hook_types.md
docs/data-sources/ip_ranges.md
docs/data-sources/user.md
docs/resources/branch_restriction.md
docs/resources/default_reviewers.md
docs/resources/hook.md
docs/resources/repository.md

IP Ranges Data Source

---

bitbucket/resource_deployment_variable.go

Prevent masking 11th deployment variable

---

bitbucket/provider.go
bitbucket/resource_deploy_key.go
bitbucket/resource_deploy_key_test.go
bitbucket/resource_ssh_key.go
docs/resources/deploy_key.md
docs/resources/ssh_key.md

Deploy Key Resource

---

docs/resources/default_reviewers.md
docs/resources/group_membership.md
docs/resources/hook.md
docs/resources/pipeline_ssh_key.md
docs/resources/project.md
docs/resources/repository.md
docs/resources/workspace_hook.md

Saw a few typos in while browsing the docs so here's a small PR to fix them up.

fix documentation typos

---

bitbucket/data_workspace_members.go
bitbucket/data_workspace_members_test.go
bitbucket/provider.go
docs/data-sources/workspace_members.md

Hi,
I've made a start here on a workspace members data source, but I can't figure out how to deal with pagination.
Would you be able to help me out?

Adding workspace members data source

---

go.mod
go.sum

Fix project resource bad request

---

bitbucket/resource_branch_restriction.go

fix branch restriction error on 404 response

---

bitbucket/provider_test.go
bitbucket/resource_pipeline_schedule.go
bitbucket/resource_pipeline_schedule_test.go

Schedule disable on create

---

docs/resources/deployment_variable.md

Deploy-var-docs

---

bitbucket/resource_deployment.go
bitbucket/resource_deployment_test.go
docs/resources/deployment.md

Deployment Import support

---

bitbucket/resource_pipeline_schedule.go
bitbucket/resource_pipeline_schedule_test.go
docs/resources/pipeline_schedule.md

Pipe-schedule-selector-type

---

bitbucket/resource_deployment_variable_test.go
go.mod
go.sum

Deploy-var-len

---

GNUmakefile
bitbucket/data_current_user.go
bitbucket/data_current_user_test.go
bitbucket/data_group.go
bitbucket/data_group_members.go
bitbucket/data_group_members_test.go
bitbucket/data_group_test.go
bitbucket/data_groups.go
bitbucket/data_groups_test.go
bitbucket/data_hook_types.go
bitbucket/data_hook_types_test.go
bitbucket/data_ip_ranges.go
bitbucket/data_ip_ranges_test.go
bitbucket/data_pipeline_oidc_config.go
bitbucket/data_pipeline_oidc_config_keys.go
bitbucket/data_pipeline_oidc_config_keys_test.go
bitbucket/data_pipeline_oidc_config_test.go
bitbucket/data_user.go
bitbucket/data_user_test.go
bitbucket/data_workspace.go
bitbucket/data_workspace_members.go
bitbucket/data_workspace_members_test.go
bitbucket/data_workspace_test.go

use ctx for data sources

---

bitbucket/data_deployment.go
bitbucket/data_deployment_test.go
bitbucket/provider.go
docs/data-sources/current_user.md
docs/data-sources/deployment.md
docs/data-sources/group_members.md
docs/data-sources/hook_types.md
docs/data-sources/ip_ranges.md
docs/data-sources/pipeline_oidc_config.md
docs/data-sources/pipeline_oidc_config_keys.md

deployment data source + doc fixes

---

bitbucket/provider.go
bitbucket/resource_repository_user_permission.go
bitbucket/resource_repository_user_permission_test.go
docs/resources/repository_user_permission.md

user repo permission resource 

---

bitbucket/resource_repository.go
bitbucket/resource_repository_test.go
docs/resources/repository.md

repository - add support for `inherit_default_merge_strategy` and `inherit_branching_model`

---

bitbucket/resource_repository.go
bitbucket/resource_repository_test.go

Fixes #141 
---
This PR attempts to extend the already existing `repository.name -> repository.slug` logic. This was not fully up to par to how Atlassian does it currently (See https://confluence.atlassian.com/bbkb/what-is-a-repository-slug-1168845069.html).
With this PR, we will allow special characters correctly, like dots in the repository name. The unit tests have been manually tested with the in-line renaming of a repo to get the expect slug output.
----
I have the feeling the Terraform Provider tries to be too 'smart', and instead we should let users provide their `.slug` as that is how the Atlassian API works. If the slug is not correct, Atlassian's API would give feedback about this:
```
{
"type": "error",
"error": {
"message": "Invalid slug. Slugs must be lowercase, …
```

Extend compute slug to conform Atlassian's slug conversion logic

---

docs/resources/branch_restriction.md

update bitbucket_branch_restriction doc with group example

---

.gitignore
bitbucket/client.go
bitbucket/provider.go
bitbucket/resource_commit_file.go
bitbucket/resource_commit_file_test.go
docs/resources/commit_file.md

I need a way to create a branch, this is needed for an empty repo with branch restriction enabled on main.
The only way i found is to use: https://developer.atlassian.com/cloud/bitbucket/rest/api-group-source/#api-repositories-workspace-repo-slug-src-post
I also changed the Bitbucket http client because I needed a different context type than "application/json".
Please give tips for improvement.

feat: add commit file

---

bitbucket/provider.go
bitbucket/resource_workspace_variable.go
bitbucket/resource_workspace_variable_test.go
docs/resources/workspace_variable.md

workspace var

---

docs/resources/repository_variable.md

bitbucket_repository var renamed to:
pipelines_enabled

Update repository_variable.md documentation

---

bitbucket/resource_hook.go
bitbucket/resource_hook_test.go
bitbucket/resource_workspace_hook.go
bitbucket/resource_workspace_hook_test.go
docs/resources/hook.md
docs/resources/workspace_hook.md

Add support for webhooks secrets (for workspace and repo level webhooks)
add more tests and docs (repo webhook docs were missing some args)
Closes #180

Webhook secret (repo and workspace)

---

bitbucket/resource_repository_variable.go
bitbucket/resource_repository_variable_test.go
docs/resources/repository_variable.md

allow importing repo vars

---

bitbucket/data_deployments.go
bitbucket/data_deployments_test.go
bitbucket/provider.go
docs/data-sources/deployments.md

deployments data source

---

bitbucket/provider.go
bitbucket/resource_project_group_permission.go
bitbucket/resource_project_group_permission_test.go
bitbucket/resource_project_user_permission.go
bitbucket/resource_project_user_permission_test.go
docs/resources/project_group_permission.md
docs/resources/project_user_permission.md

project user and group permission resources

---

bitbucket/resource_branching_model.go

BranchingModel: use_mainbranch field is required in JSON

---

bitbucket/resource_repository.go
docs/resources/repository.md

Fixes https://github.com/DrFaust92/terraform-provider-bitbucket/issues/216

Allow repository mainbranch configuration
