DrFaust92/terraform-provider-bitbucket

bitbucket/resource_project.go
bitbucket/resource_repository.go
docs/resources/project.md

Supersedes #1 (need to run `make fmt`)

Import Project support

---

bitbucket/resource_pipeline_ssh_known_host.go
bitbucket/resource_pipeline_ssh_known_host_test.go
docs/resources/pipeline_ssh_known_host.md

This PR fixes the input validation for the `public_key.key_type` to work with values Bitbucket actually use for their known host entities.
The values have been retrieved by using the `/pipelines_config/ssh/known_hosts/?pagelen=100` endpoint. Where the added known host is tested with an correct SSH pipeline connection.
---
Fixes #70

fix(kown_host) allowed public key type values

---

.gitignore
main.go

This PR adds support for attaching a [`go-delve`](https://github.com/go-delve/delve) session to the codebase using a `-debug` flag. This follows the documentation of https://developer.hashicorp.com/terraform/plugin/debugging where the implementation of https://developer.hashicorp.com/terraform/plugin/sdkv2/debugging is used.
Together with a local `.terraformrc` and a local backend, I can live test and debug (with VSCode break points) this provider. I thought this might be a nice addition for everyone.

chore: add support for local provider debugging

---

docs/data-sources/current_user.md
docs/data-sources/user.md
docs/resources/default_reviewers.md
docs/resources/project_default_reviewers.md

This replaces the removed `"account_id"` property with `"uuid"`. I also fixed some smaller grammar issues in the user docs.

docs(user): use uuid instead of account_id

---

docs/resources/project_branching_model.md

This fixes a small but essential typo in the project-branching-model documentation.

docs(project-branching-model): fix small typo in example

---

bitbucket/resource_branching_model.go

This PR makes sure to reset the “specific branch” model type by setting the “name” to `null` when it is no longer defined.
Fixes #104

fix(branching_model): fix specific branch to main branch update

---

bitbucket/resource_repository.go
bitbucket/resource_repository_test.go

Depended on the new API version including https://github.com/DrFaust92/bitbucket-go-client/pull/12
> === RUN   TestAccBitbucketRepository_slug
--- PASS: TestAccBitbucketRepository_slug (6.38s)
PASS
ok      github.com/terraform-providers/terraform-provider-bitbucket/bitbucket   6.399s
fixes #95

fix(repository): set actual slug property instead of the repository name

---

README.md
bitbucket/client.go
bitbucket/provider.go
docs/index.md
go.mod

Authenticating using a bare OAuth2 Access Token is not very convenient since it has limited validity and needs to be aquired by other means outside of the provider.
Bitbucket supports authentication via Client Credentials Grant, which is easier to use.
This change adds support for the `oauth_client_id` and `oauth_client_secret` provider configuration fields (and environment variables) and updates the provider documentation.
This is an alternative to the existing auth via `username`/`password` or `oauth_token`.

feat(auth): add support for OAuth2 Client Credentials

---

bitbucket/error.go
bitbucket/resource_branch_restriction.go

This PR makes sure that the HTTP errors (`GenericSwaggerError`) is actually handled whenever it is returned. 
We differentiate between normal `error` objects and `GenericSwaggerError` by testing a type cast. I tried to wrap this logic in a helper function we can easily use throughout any of the resources.
----
Example error output:
**REST Error**
```
bitbucket_branch_restriction.development: Creating...
╷
│ Error: 409 Conflict: a branch restriction with that kind (force) and branch type (development) already exists (id=34493232)
│ 
│   with bitbucket_branch_restriction.development,
│   on example.tf line 13, in resource "bitbucket_branch_restriction" "development":
│   13: resource "bitbucket_branch_restriction" "development" {
│ 
╵
```
**Auth Error**
``` …
```

fix(branch-restriction): handle http errors

---

bitbucket/data_workspace_test.go

This PR makes the data_workspace_test is a bit more stable. Previously, the test was based on a very specific Workspace set up, where `is_private` has to be set to `true`.
To make this test less dependent on a specific set up of a manual created workspace. I now only test if this attribute is set.
fixes #127

fix(data_workspace): only test on attribute existence

---

bitbucket/data_current_user.go
bitbucket/data_hook_types.go
bitbucket/data_user.go
bitbucket/data_workspace.go
bitbucket/error.go
bitbucket/resource_branch_restriction.go
bitbucket/resource_default_reviewers.go
bitbucket/resource_deploy_key.go
bitbucket/resource_deployment_variable.go
bitbucket/resource_forked_repository.go
bitbucket/resource_pipeline_schedule.go
bitbucket/resource_pipeline_ssh_key.go
bitbucket/resource_pipeline_ssh_known_host.go
bitbucket/resource_project.go
bitbucket/resource_project_default_reviewers.go
bitbucket/resource_repository.go
bitbucket/resource_repository_variable.go
bitbucket/resource_ssh_key.go

This is a continuation of the work done in https://github.com/DrFaust92/terraform-provider-bitbucket/pull/125
---
Handle all HTTP Error responses (`GenericSwaggerError`) wherever the API Client is used. So the scope of this ticket is only the usage of API Client. The following changes are applied in this PR:
- Return a `error` object instead of the `Diagnostics` object to better control the error aggregation (for example, needed in `resource_forked_repository.go`). 
- Remove redundant error messages and simply propagate the error message.
- Make sure the resource reset based on `res.StatusCode == http.StatusNotFound` happens after the HTTP Error handling. This is because HTTP 404 is also thrown as a `GenericSwaggerError` in the API client.
Fixes #93
---
All, except one, acceptance test …

fix: handle http errors of api client

---

docs/index.md

This was actually mentioned briefly in the past, but I accidently removed it in https://github.com/DrFaust92/terraform-provider-bitbucket/pull/121.

docs(provider): mention `BITBUCKET_PASSWORD` environment variable

---

docs/resources/workspace_hook.md

I stumbled across the incorrect example which seemed to be copied from the `bitbucket_hook` resource documentation and added documentation for missing arguments and exported attributes while I was at it.

docs(workspace-hook): document all attributes

---

bitbucket/resource_repository.go

After updating from version 2.22.0 to 2.29.0 i get always a 404 error, on existing repos: 
```
│ Error: 404 Not Found: Not found
│
│   with module.repos["example"].bitbucket_repository.this,
│   on modules/bitbucket-repo/main.tf line 1, in resource "bitbucket_repository" "this":
│    1: resource "bitbucket_repository" "this" {
```
This is related to this commit: https://github.com/DrFaust92/terraform-provider-bitbucket/commit/c443cd1e07c19bc5c56ecafcfc105a319def1e2a#diff-3bd5177b56ea90e3601af4cf3155bea57949347bead0d21d6526c518f499f916L314
We are not using the bitbucket piplines.
maybe related to: #141

ignore error when pipeline config not found

---

docs/resources/hook.md

https://support.atlassian.com/bitbucket-cloud/docs/event-payloads/ has more details about what events to use and their names

replacing the hooks event link with more appropiate one

---

bitbucket/resource_forked_repository.go

This is a fix for the bug reported in issue https://github.com/DrFaust92/terraform-provider-bitbucket/issues/178.

ignore 404 error when forked repo pipeline config not found

---

bitbucket/resource_project.go
bitbucket/resource_project_test.go

Fix Project update

---

docs/resources/repository_group_permission.md

Using the `bitbucket_repository_group_permission` resource when authenticating with Bitbucket using OAuth gives a 403 error. It only works when authenticating via an app password.
This PR documents this limitation.

document repo group permissions oauth limitation

---

bitbucket/data_group_members.go
bitbucket/data_group_members_test.go
bitbucket/data_workspace_members.go
bitbucket/data_workspace_members_test.go
docs/data-sources/group_members.md
docs/data-sources/workspace_members.md

Expand results for group members + move to use sdk

---

bitbucket/data_current_user.go
bitbucket/data_deployments.go
bitbucket/data_hook_types.go
bitbucket/data_user.go
bitbucket/data_workspace.go
bitbucket/data_workspace_members.go
bitbucket/error.go
bitbucket/resource_branch_restriction.go
bitbucket/resource_commit_file.go
bitbucket/resource_default_reviewers.go
bitbucket/resource_deploy_key.go
bitbucket/resource_deployment.go
bitbucket/resource_deployment_variable.go
bitbucket/resource_forked_repository.go
bitbucket/resource_pipeline_schedule.go
bitbucket/resource_pipeline_ssh_key.go
bitbucket/resource_pipeline_ssh_known_host.go
bitbucket/resource_project.go
bitbucket/resource_project_default_reviewers.go
bitbucket/resource_repository.go
bitbucket/resource_repository_test.go
bitbucket/resource_repository_variable.go
bitbucket/resource_ssh_key.go
bitbucket/resource_workspace_variable.go

This PR makes sure that an authorization error (`401 Unauthorized`) is at least shown to the end user.
---
Bitbucket responses, mainly headers and error codes, seem to have completely changed. For the unauthorized response, the `Content-Type` was changed to `"text/plain"` where no HTTP-body is returned any more.
Because of this, the client's decoding fails (see https://github.com/DrFaust92/bitbucket-go-client/blob/main/client.go#L387), and the original Bitbucket API error is no longer passed to the Terraform code.
To overcome this issue, I now rely on the raw HTTP Response and always log the original HTTP Code. The main files to review are the tests and the `bitbucket/error.go` file.
**Authorization error**
```
╷
│ Error: 401 Unauthorized: 
│ 
│   with bitbucket_repository.that,
│   on …
```

fix: make sure the authorization error is correctly shown to the end user

---

docs/resources/branch_restriction.md

A small PR to show that users use Bitbucket usernames, instead of `uuid`s.
Closes #53

chore(doc): extend branch-restriction documentation example to show username usage

---

bitbucket/resource_repository.go

Fixes #96 
After a change to the `owner` or `name` field of a `bitbucket_repository` resource, two things need to change:
- Any subsequent Bitbucket API requests _within the current Terraform run_ should use the new owner and name. This avoids a 404 error.
- The internal resource ID tracked in Terraform state needs to reflect the new owner/name. This ensures that _subsequent Terraform runs_ will work correctly.

Renaming bitbucket_repository fails with 404 (not found) error

---

bitbucket/resource_branching_model.go

Fix multiple bugs in handling of branch_types.enabled

---

bitbucket/resource_repository_user_permission.go

This fixes a nuisance issue I noticed. With `bitbucket_repository_user_permission`, if `user_id` is a user _name_ (rather than a UUID), the changes apply without error, but subsequent runs of `terraform plan` and `terraform apply` always show a change needs to be applied.
I noticed that the provider [documentation](https://registry.terraform.io/providers/DrFaust92/bitbucket/latest/docs/resources/repository_user_permission#argument-reference) explicitly states that `user_id` is "The UUID of the user.", so it seems best to disallow the use of user names. This PR does that. As a bonus, the error message provides the UUID of the user to make it easy to fix the code.
```
user_permissions = {
"my-user-name" = "write",
"{aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa}" = "write",
}
```

Prevent using user name with bitbucket_repository_user_permission. Must be UUID.

---

bitbucket/resource_branching_model.go

Attempting to enable the production branch_type never seems to get "fixed"

---

bitbucket/resource_project_branching_model.go

As per: https://developer.atlassian.com/cloud/bitbucket/rest/api-group-branching-model/#api-repositories-workspace-repo-slug-branching-model-settings-get
`projects/PROJECT/branching-model/settings` will return more consistent results compared to `projects/PROJECT/branching-model`.
For the same repo (no settings changed):
`projects/PROJECT/branching-model/settings`
```
{"type": "branching_model_settings", "links": {"self": {"href": "https://api.bitbucket.org/2.0/workspaces/MY_ORG/projects/MY_PROJECT/branching-model/settings"}}, "branch_types": [{"enabled": true, "kind": "release", "prefix": "release/"}, {"enabled": true, "kind": "hotfix", "prefix": "hotfix/"}, {"enabled": false, "kind": "feature", "prefix": "feature/"}, {"enabled": true, "kind": "bugfix", "prefix": "bugfix/"}], …
```

Use more consistent endpoint for project branching models

---

bitbucket/error.go
bitbucket/resource_deploy_key.go
bitbucket/resource_deployment_variable.go
bitbucket/resource_forked_repository.go
bitbucket/resource_pipeline_schedule.go
bitbucket/resource_pipeline_ssh_key.go
bitbucket/resource_pipeline_ssh_known_host.go
bitbucket/resource_project.go
bitbucket/resource_repository.go
bitbucket/resource_repository_variable.go
bitbucket/resource_ssh_key.go
bitbucket/resource_workspace_variable.go

This PR addresses a few issues I've experienced with the provider when using OAuth. Currently, most OAuth related errors result in a panic and the provider crashing. This can be replicated on the current version by doing the following:
- Using the key/secret of an OAuth provider which doesn't have a callback URL defined
- Using the key/secret of an OAuth provider which doesn't have the "This is a private consumer" option ticked
- Running `terraform apply` using incorrect OAuth credentials
- Running `terraform plan` using incorrect OAuth credentials when there is at least 1 bitbucket resource in the state
This is the result of a number of resources referencing `res.StatusCode` after making an API call which can return a nil http response. I've currently fixed this by just adding a nil …

Improve oauth error handling
